import '../entities/cost_consumption.dart';
import '../entities/cost_layer.dart';
import '../enums/cost_valuation_method.dart';

/// Calculation result when consuming inventory quantity from cost layers.
class LayerConsumptionResult {
  const LayerConsumptionResult({
    required this.consumptions,
    required this.totalCost,
    required this.effectiveUnitCost,
    required this.isShortage,
    required this.shortageQty,
  });

  final List<CostConsumption> consumptions;
  final double totalCost;
  final double effectiveUnitCost;
  final bool isShortage;
  final double shortageQty;
}

/// Service governing inventory cost layers creation, valuation, consumption, and reversal.
abstract class CostLayerService {
  /// Creates a new cost layer for an incoming stock movement line.
  Future<void> createLayer(CostLayer layer);

  /// Consumes quantity from active cost layers for [itemCode] using the specified [method].
  ///
  /// Returns a [LayerConsumptionResult] containing details of layer consumptions,
  /// calculated total cost, effective average unit cost, and any unfulfilled shortage.
  Future<LayerConsumptionResult> consumeLayers({
    required String itemCode,
    required double quantity,
    required CostValuationMethod method,
    required String issueLineUuid,
    required String movementType,
    String? warehouseId,
    String? companyId,
  });

  /// Reverses all consumptions generated by an outgoing movement line (e.g. on line edit/delete).
  /// Restores consumed quantities back to their respective cost layers.
  Future<void> reverseConsumptions(String issueLineUuid);

  /// Deletes cost layer(s) generated by an incoming movement UUID (e.g. on receipt delete)
  /// and restores any downstream consumptions if applicable.
  Future<void> reverseLayer(String movementUuid);

  /// Computes current weighted average cost per main unit for [itemCode].
  Future<double> getWeightedAverageCost(String itemCode, {String? warehouseId});

  /// Returns open (non-closed) active cost layers for [itemCode].
  Future<List<CostLayer>> getOpenLayers(String itemCode, {String? warehouseId});
}
