import 'package:drift/drift.dart';
import 'package:stock_count/modules/accounting/shared/data/database/accounting_database.dart';
import 'package:stock_count/modules/inventory/shared/data/database/inventory_database.dart';

/// Centralized domain validator enforcing referential integrity and controlled deletion
/// rules across inventory and accounting tables to prevent orphan financial records.
class FinancialReferentialIntegrityValidator {
  FinancialReferentialIntegrityValidator({
    required InventoryDatabase invDb,
    AccountingDatabase? accDb,
    String Function()? readCompanyId,
  })  : _invDb = invDb,
        _accDb = accDb,
        _readCompanyId = readCompanyId;

  final InventoryDatabase _invDb;
  final AccountingDatabase? _accDb;
  final String Function()? _readCompanyId;

  String? get _companyId => _readCompanyId?.call();

  /// 1. CostLayer Deletion Guard:
  /// Validates that a CostLayer does NOT have dependent CostConsumptions before deletion.
  Future<void> validateCostLayerDeletion(String layerUuid) async {
    final compId = _companyId;
    final consumptions = await (_invDb.select(_invDb.inventoryCostConsumptions)
          ..where((t) =>
              t.layerUuid.equals(layerUuid) &
              (compId != null ? t.companyId.equals(compId) : const Constant(true))))
        .get();

    if (consumptions.isNotEmpty) {
      throw StateError(
        'Referential Integrity Error: Cannot delete CostLayer ($layerUuid) because ${consumptions.length} dependent CostConsumption records exist.',
      );
    }
  }

  /// 2. CostLayer Creation Guard:
  /// Validates that a CostLayer has a valid, non-empty movementUuid and source.
  void validateCostLayerCreation({
    required String movementUuid,
    required String itemCode,
    required double receivedQty,
  }) {
    if (movementUuid.trim().isEmpty) {
      throw StateError(
        'Referential Integrity Error: Cannot create CostLayer for item ($itemCode) without a valid source movementUuid.',
      );
    }
    if (itemCode.trim().isEmpty) {
      throw StateError(
        'Referential Integrity Error: Cannot create CostLayer without a valid itemCode.',
      );
    }
  }

  /// 3. CostConsumption Creation Guard:
  /// Validates that the target CostLayer exists and is active before inserting a consumption.
  Future<void> validateCostConsumptionCreation({
    required String layerUuid,
    required String issueLineUuid,
  }) async {
    if (layerUuid.trim().isEmpty) {
      throw StateError('Referential Integrity Error: CostConsumption must reference a valid layerUuid.');
    }
    if (issueLineUuid.trim().isEmpty) {
      throw StateError('Referential Integrity Error: CostConsumption must reference a valid issueLineUuid.');
    }

    final compId = _companyId;
    final layer = await (_invDb.select(_invDb.inventoryCostLayers)
          ..where((t) =>
              t.uuid.equals(layerUuid) &
              (compId != null ? t.companyId.equals(compId) : const Constant(true))))
        .getSingleOrNull();

    if (layer == null) {
      throw StateError(
        'Referential Integrity Error: Target CostLayer ($layerUuid) does not exist.',
      );
    }
  }

  /// 4. JournalEntry Deletion Guard:
  /// Validates that a JournalEntry can be deleted. If posted or tied to operational source, deletion is BLOCKED.
  Future<void> validateJournalEntryDeletion(String entryUuid) async {
    final accDb = _accDb;
    if (accDb == null) return;

    final compId = _companyId;
    final entry = await (accDb.select(accDb.journalEntries)
          ..where((t) =>
              t.uuid.equals(entryUuid) &
              (compId != null ? t.companyId.equals(compId) : const Constant(true))))
        .getSingleOrNull();

    if (entry == null) return;

    if (entry.isPosted) {
      throw StateError(
        'Referential Integrity Error: Cannot delete posted JournalEntry ($entryUuid). Historical posted accounting records cannot be physically deleted.',
      );
    }

    if (entry.sourceType != null && entry.sourceType!.isNotEmpty) {
      throw StateError(
        'Referential Integrity Error: Cannot delete JournalEntry ($entryUuid) generated by operational source (${entry.sourceType}:${entry.sourceId}).',
      );
    }
  }

  /// 5. JournalLine Creation Guard:
  /// Validates that a JournalLine references an existing JournalEntry.
  Future<void> validateJournalLineCreation({
    required String entryUuid,
    required String accountUuid,
  }) async {
    if (entryUuid.trim().isEmpty) {
      throw StateError('Referential Integrity Error: JournalLine must reference a non-empty entryUuid.');
    }
    if (accountUuid.trim().isEmpty) {
      throw StateError('Referential Integrity Error: JournalLine must reference a valid accountUuid.');
    }

    final accDb = _accDb;
    if (accDb == null) return;

    final compId = _companyId;
    final entry = await (accDb.select(accDb.journalEntries)
          ..where((t) =>
              t.uuid.equals(entryUuid) &
              (compId != null ? t.companyId.equals(compId) : const Constant(true))))
        .getSingleOrNull();

    if (entry == null) {
      throw StateError('Referential Integrity Error: Target JournalEntry ($entryUuid) does not exist.');
    }
  }

  /// 6. Warehouse Deletion Guard:
  /// Validates that a Warehouse can be deleted. If open cost layers, product warehouse stocks, or movement lines exist, deletion is BLOCKED.
  Future<void> validateWarehouseDeletion(String warehouseUuid) async {
    final compId = _companyId;

    final openLayers = await (_invDb.select(_invDb.inventoryCostLayers)
          ..where((t) =>
              t.warehouseId.equals(warehouseUuid) &
              t.closed.equals(0) &
              (compId != null ? t.companyId.equals(compId) : const Constant(true))))
        .get();

    if (openLayers.isNotEmpty) {
      throw StateError(
        'Referential Integrity Error: Cannot delete Warehouse ($warehouseUuid) because ${openLayers.length} open CostLayer(s) exist in this warehouse.',
      );
    }

    final stocks = await (_invDb.select(_invDb.productWarehouseStocks)
          ..where((t) =>
              t.warehouseId.equals(warehouseUuid) &
              t.onHandQty.isBiggerThanValue(0.0001) &
              (compId != null ? t.companyId.equals(compId) : const Constant(true))))
        .get();

    if (stocks.isNotEmpty) {
      throw StateError(
        'Referential Integrity Error: Cannot delete Warehouse ($warehouseUuid) because non-zero stock balances exist.',
      );
    }
  }

  /// 7. Product Deletion Guard:
  /// Validates that a Product (itemCode) can be deleted. If open cost layers or posted movement lines exist, deletion is BLOCKED.
  Future<void> validateProductDeletion(String itemCode) async {
    final compId = _companyId;

    final openLayers = await (_invDb.select(_invDb.inventoryCostLayers)
          ..where((t) =>
              t.itemCode.equals(itemCode) &
              t.closed.equals(0) &
              (compId != null ? t.companyId.equals(compId) : const Constant(true))))
        .get();

    if (openLayers.isNotEmpty) {
      throw StateError(
        'Referential Integrity Error: Cannot delete Product ($itemCode) because ${openLayers.length} open CostLayer(s) exist for this item.',
      );
    }

    final postedLines = await (_invDb.select(_invDb.stockMovementLines)
          ..where((t) =>
              t.itemCode.equals(itemCode) &
              t.postedAt.isNotNull()))
        .get();

    if (postedLines.isNotEmpty) {
      throw StateError(
        'Referential Integrity Error: Cannot delete Product ($itemCode) because ${postedLines.length} posted movement lines exist.',
      );
    }
  }

  /// 8. Document Deletion Guard:
  /// Validates that a document (receipt, issue, transfer, return) can be deleted. Posted documents CANNOT be deleted.
  Future<void> validateDocumentDeletion({
    required String documentId,
    required String documentType,
    required String status,
  }) async {
    if (status == 'posted') {
      throw StateError(
        'Referential Integrity Error: Cannot delete posted document ($documentType: $documentId). Posted financial data cannot be physically deleted.',
      );
    }
  }
}
